### ISSUE TITLE
Market Data real time update doesn't work

### ISSUE THREAD

**Issue by oasuncion** [oasuncion/tradista#152]
When activating the market data real time update on the repo trading dashboards, the activation fails with this exception:

```
11:50:41,036 SEVERE [jakarta.enterprise.resource.webcontainer.faces.context] (default task-1) jakarta.faces.component.search.ComponentNotFoundException: Cannot find component for expressions ":quotesCashflowsTabs:quotesCashflowsTabs:quotesListDataTable" referenced from "dashboardForm:quotesCashflowsTabs:poll".: jakarta.faces.component.search.ComponentNotFoundException: Cannot find component for expressions ":quotesCashflowsTabs:quotesCashflowsTabs:quotesListDataTable" referenced from "dashboardForm:quotesCashflowsTabs:poll".
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.component.search.SearchExpressionHandlerImpl.resolveClientIds(SearchExpressionHandlerImpl.java:116)
	at deployment.app-2.2.0-SNAPSHOT.ear.web-2.2.0-SNAPSHOT.war//org.primefaces.expression.SearchExpressionUtils.resolveClientIdsAsString(SearchExpressionUtils.java:132)
	at deployment.app-2.2.0-SNAPSHOT.ear.web-2.2.0-SNAPSHOT.war//org.primefaces.util.AjaxRequestBuilder.addExpressions(AjaxRequestBuilder.java:156)
	at deployment.app-2.2.0-SNAPSHOT.ear.web-2.2.0-SNAPSHOT.war//org.primefaces.util.AjaxRequestBuilder.update(AjaxRequestBuilder.java:148)
	at deployment.app-2.2.0-SNAPSHOT.ear.web-2.2.0-SNAPSHOT.war//org.primefaces.renderkit.CoreRenderer.preConfiguredAjaxRequestBuilder(CoreRenderer.java:468)
	at deployment.app-2.2.0-SNAPSHOT.ear.web-2.2.0-SNAPSHOT.war//org.primefaces.renderkit.CoreRenderer.preConfiguredAjaxRequestBuilder(CoreRenderer.java:457)
	at deployment.app-2.2.0-SNAPSHOT.ear.web-2.2.0-SNAPSHOT.war//org.primefaces.component.poll.PollRenderer.encodeEnd(PollRenderer.java:64)
	at jakarta.faces.api//jakarta.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:586)
	at jakarta.faces.api//jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1442)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:594)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:158)
	at jakarta.faces.api//jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1266)
	at jakarta.faces.api//jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
	at deployment.app-2.2.0-SNAPSHOT.ear.web-2.2.0-SNAPSHOT.war//org.primefaces.component.api.UITabPanel.visitTree(UITabPanel.java:947)
	at jakarta.faces.api//jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
	at jakarta.faces.api//jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
	at jakarta.faces.api//jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
	at jakarta.faces.api//jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
	at jakarta.faces.api//jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
	at jakarta.faces.api//jakarta.faces.component.UIForm.visitTree(UIForm.java:344)
	at jakarta.faces.api//jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
	at jakarta.faces.api//jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:392)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:307)
	at deployment.app-2.2.0-SNAPSHOT.ear.web-2.2.0-SNAPSHOT.war//org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:61)
	at deployment.app-2.2.0-SNAPSHOT.ear.web-2.2.0-SNAPSHOT.war//org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:61)
	at jakarta.faces.api//jakarta.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1086)
	at jakarta.faces.api//jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1435)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:415)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:162)
	at jakarta.faces.api//jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:93)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:178)
	at jakarta.faces.api//jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:692)
	at jakarta.faces.api//jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.smallrye.opentracing-contrib//io.smallrye.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:69)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.security.elytron-web.undertow-server@3.0.0.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.lambda$handleRequest$1(ElytronRunAsHandler.java:68)
	at org.wildfly.security.elytron-base@2.0.0.Final//org.wildfly.security.auth.server.FlexibleIdentityAssociation.runAsFunctionEx(FlexibleIdentityAssociation.java:103)
	at org.wildfly.security.elytron-base@2.0.0.Final//org.wildfly.security.auth.server.Scoped.runAsFunctionEx(Scoped.java:161)
	at org.wildfly.security.elytron-base@2.0.0.Final//org.wildfly.security.auth.server.Scoped.runAs(Scoped.java:73)
	at org.wildfly.security.elytron-web.undertow-server@3.0.0.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.handleRequest(ElytronRunAsHandler.java:67)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.core@2.3.0.Final//io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.core@2.3.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.3.0.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.core@2.3.0.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.core@2.3.0.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at org.wildfly.security.elytron-web.undertow-server-servlet@3.0.0.Final//org.wildfly.elytron.web.undertow.server.servlet.CleanUpHandler.handleRequest(CleanUpHandler.java:38)
	at io.undertow.core@2.3.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@27.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.3.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@27.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.core@2.3.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@27.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
	at org.wildfly.extension.undertow@27.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
	at org.wildfly.extension.undertow@27.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
	at org.wildfly.extension.undertow@27.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
	at org.wildfly.extension.undertow@27.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
	at io.undertow.core@2.3.0.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:391)
	at io.undertow.core@2.3.0.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at org.jboss.xnio@3.8.8.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**To Reproduce**
1. Go to the GC or Specific Repo trading dashboard
2. Load or create a trade, for which related securities have their prices updated in Tradista in real time
3. Tick "Real Time" in the "Quotes" panel
4. The above exception is thrown and the real time update activation doesn't work.

**Expected behavior**
No exception and the real time update activated

**Environment:**
 - Version 2.2.0-SNAPSHOT

**Comment by oasuncion** [comment]
Will be included in v2.2.0
