### ISSUE TITLE
JavaFX client crashes during the loading animation on Linux

### ISSUE THREAD

**Issue by oasuncion** [oasuncion/tradista#37]
The JavaFX client crashes during the loading animation on Linux.

Here is the error:

> juin 19, 2022 10:43:31 PM org.wildfly.naming.client.Version <clinit>
> INFO: WildFly Naming version 1.0.11.Final
> juin 19, 2022 10:43:31 PM org.wildfly.security.Version <clinit>
> INFO: ELY00001: WildFly Elytron version 1.10.4.Final
> juin 19, 2022 10:43:31 PM org.xnio.Xnio <clinit>
> INFO: XNIO version 3.7.3.Final
> juin 19, 2022 10:43:32 PM org.xnio.nio.NioXnio <clinit>
> INFO: XNIO NIO Implementation Version 3.7.3.Final
> juin 19, 2022 10:43:32 PM org.jboss.threads.Version <clinit>
> INFO: JBoss Threads version 2.3.3.Final
> juin 19, 2022 10:43:32 PM org.jboss.remoting3.EndpointImpl <clinit>
> INFO: JBoss Remoting version 5.0.15.Final
> javax.naming.CommunicationException: WFNAM00018: Failed to connect to remote host [Root exception is javax.security.sasl.SaslException: Authentication failed: none of the mechanisms presented by the server (PLAIN) are supported]
> 	at org.wildfly.naming.client.remote.RemoteNamingProvider.getPeerIdentityForNaming(RemoteNamingProvider.java:110)
> 	at org.wildfly.naming.client.remote.RemoteNamingProvider.getPeerIdentityForNaming(RemoteNamingProvider.java:53)
> 	at org.wildfly.naming.client.NamingProvider.getPeerIdentityForNamingUsingRetry(NamingProvider.java:105)
> 	at org.wildfly.naming.client.remote.RemoteNamingProvider.getPeerIdentityForNamingUsingRetry(RemoteNamingProvider.java:91)
> 	at org.wildfly.naming.client.remote.RemoteContext.lambda$lookupNative$0(RemoteContext.java:189)
> 	at org.wildfly.naming.client.NamingProvider.performExceptionAction(NamingProvider.java:222)
> 	at org.wildfly.naming.client.remote.RemoteContext.performWithRetry(RemoteContext.java:100)
> 	at org.wildfly.naming.client.remote.RemoteContext.lookupNative(RemoteContext.java:188)
> 	at org.wildfly.naming.client.AbstractFederatingContext.lookup(AbstractFederatingContext.java:74)
> 	at org.wildfly.naming.client.AbstractFederatingContext.lookup(AbstractFederatingContext.java:60)
> 	at org.wildfly.naming.client.WildFlyRootContext.lookup(WildFlyRootContext.java:144)
> 	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
> 	at finance.tradista.core.common.a.a.a(TradistaServiceLocator.java:1765)
> 	at finance.tradista.core.common.a.a.x(TradistaServiceLocator.java:771)
> 	at finance.tradista.core.user.service.a.<init>(UserBusinessDelegate.java:39)
> 	at finance.tradista.core.user.ui.controller.LoginController.initialize(LoginController.java:47)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
> 	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
> 	at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
> 	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2591)
> 	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
> 	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3237)
> 	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3194)
> 	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3163)
> 	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3136)
> 	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3113)
> 	at javafx.fxml/javafx.fxml.FXMLLoader.load(FXMLLoader.java:3106)
> 	at finance.tradista.core.common.ui.view.MainEntry.c(MainEntry.java:198)
> 	at finance.tradista.core.common.ui.view.MainEntry.start(MainEntry.java:233)
> 	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
> 	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
> 	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
> 	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
> 	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
> 	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> Caused by: javax.security.sasl.SaslException: Authentication failed: none of the mechanisms presented by the server (PLAIN) are supported
> 	at org.jboss.remoting3.remote.ClientConnectionOpenListener$Capabilities.handleEvent(ClientConnectionOpenListener.java:444)
> 	at org.jboss.remoting3.remote.ClientConnectionOpenListener$Capabilities.handleEvent(ClientConnectionOpenListener.java:242)
> 	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
> 	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
> 	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
> 	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
> 	at ...asynchronous invocation...(Unknown Source)
> 	at org.jboss.remoting3.EndpointImpl.connect(EndpointImpl.java:599)
> 	at org.jboss.remoting3.EndpointImpl.connect(EndpointImpl.java:565)
> 	at org.jboss.remoting3.ConnectionInfo$None.getConnection(ConnectionInfo.java:82)
> 	at org.jboss.remoting3.ConnectionInfo.getConnection(ConnectionInfo.java:55)
> 	at org.jboss.remoting3.EndpointImpl.doGetConnection(EndpointImpl.java:499)
> 	at org.jboss.remoting3.EndpointImpl.getConnectedIdentity(EndpointImpl.java:445)
> 	at org.jboss.remoting3.UncloseableEndpoint.getConnectedIdentity(UncloseableEndpoint.java:52)
> 	at org.wildfly.naming.client.remote.RemoteNamingProvider.getFuturePeerIdentityPrivileged(RemoteNamingProvider.java:151)
> 	at org.wildfly.naming.client.remote.RemoteNamingProvider.lambda$getFuturePeerIdentity$0(RemoteNamingProvider.java:138)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at org.wildfly.naming.client.remote.RemoteNamingProvider.getFuturePeerIdentity(RemoteNamingProvider.java:138)
> 	at org.wildfly.naming.client.remote.RemoteNamingProvider.getPeerIdentity(RemoteNamingProvider.java:126)
> 	at org.wildfly.naming.client.remote.RemoteNamingProvider.getPeerIdentityForNaming(RemoteNamingProvider.java:106)
> 	... 44 more
> juin 19, 2022 10:43:34 PM org.jboss.ejb.client.EJBClient <clinit>
> INFO: JBoss EJB Client version 4.0.23.Final
> Exception in Application start method
> java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
> 	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
> Caused by: java.lang.RuntimeException: Exception in Application start method
> 	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
> 	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> Caused by: MediaException: UNKNOWN : com.sun.media.jfxmedia.MediaException: Could not create player! : com.sun.media.jfxmedia.MediaException: Could not create player!
> 	at javafx.media/javafx.scene.media.MediaException.exceptionToMediaException(MediaException.java:146)
> 	at javafx.media/javafx.scene.media.MediaPlayer.init(MediaPlayer.java:518)
> 	at javafx.media/javafx.scene.media.MediaPlayer.<init>(MediaPlayer.java:421)
> 	at finance.tradista.core.common.ui.b.a.a(TradistaGUIUtil.java:889)
> 	at finance.tradista.core.common.ui.view.MainEntry.b(MainEntry.java:191)
> 	at finance.tradista.core.common.ui.view.MainEntry.start(MainEntry.java:236)
> 	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
> 	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
> 	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
> 	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
> 	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
> 	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
> 	... 1 more
> Caused by: com.sun.media.jfxmedia.MediaException: Could not create player!
> 	at javafx.media/com.sun.media.jfxmediaimpl.NativeMediaManager.getPlayer(NativeMediaManager.java:295)
> 	at javafx.media/com.sun.media.jfxmedia.MediaManager.getPlayer(MediaManager.java:118)
> 	at javafx.media/javafx.scene.media.MediaPlayer.init(MediaPlayer.java:474)
> 	... 13 more
> Exception running application finance.tradista.core.common.ui.view.MainEntry

### Test case

Start the JavaFX Client (TradistaClient.sh) on Linux.

### Actual results:

Tradista JavaFX client crashes during the loading animation on Linux, with the error above.

### Expected results:

Tradista JavaFX client starts properly.

**Comment by oasuncion** [comment]
The issue has been fixed with the upgrade of javaFX to 18.0.1.
The fix will be part of v1.0.4.
