### ISSUE TITLE
NullPointerException when selecting a quote date for Equity trades

### ISSUE THREAD

**Issue by oasuncion** [oasuncion/tradista#74]
There is a NullPointerException when selecting a quote date in the equity trades window, if the exchange of the equity doesn't have a calendar.

**To Reproduce**
1. Go to the Equity Trade window
2. Select an equity linked to an exchange without calendar
3. Click on the Quote Date calendar in the "_Quotes_" tab

**Expected behavior**
The calendar should appear without any error. A log warning should say that the exchange has no calendar.

**Environment:**

 - Version: 1.0.6

Stack trace:

> Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
> 	at finance.tradista.security.equity.service.EquityTradeBusinessDelegate.isBusinessDay(EquityTradeBusinessDelegate.java:73)
> 	at finance.tradista.security.equity.ui.controller.EquityTradeDefinitionController$8$1.isAvailable(EquityTradeDefinitionController.java:411)
> 	at finance.tradista.security.equity.ui.controller.EquityTradeDefinitionController$8$1.updateItem(EquityTradeDefinitionController.java:425)
> 	at javafx.controls@18.0.1/com.sun.javafx.scene.control.DatePickerContent.updateDayCells(DatePickerContent.java:526)
> 	at javafx.controls@18.0.1/com.sun.javafx.scene.control.DatePickerContent.updateValues(DatePickerContent.java:394)
> 	at javafx.controls@18.0.1/com.sun.javafx.scene.control.DatePickerContent.refresh(DatePickerContent.java:387)
> 	at javafx.controls@18.0.1/com.sun.javafx.scene.control.DatePickerContent.<init>(DatePickerContent.java:220)
> 	at javafx.controls@18.0.1/javafx.scene.control.skin.DatePickerSkin.getPopupContent(DatePickerSkin.java:179)
> 	at javafx.controls@18.0.1/javafx.scene.control.skin.ComboBoxPopupControl.show(ComboBoxPopupControl.java:245)
> 	at javafx.controls@18.0.1/javafx.scene.control.skin.DatePickerSkin.show(DatePickerSkin.java:195)
> 	at javafx.controls@18.0.1/javafx.scene.control.skin.ComboBoxBaseSkin.lambda$new$6(ComboBoxBaseSkin.java:128)
> 	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
> 	at javafx.controls@18.0.1/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(LambdaMultiplePropertyChangeListenerHandler.java:88)
> 	at javafx.base@18.0.1/javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:86)
> 	at javafx.base@18.0.1/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
> 	at javafx.base@18.0.1/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
> 	at javafx.base@18.0.1/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:78)
> 	at javafx.base@18.0.1/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:103)
> 	at javafx.base@18.0.1/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
> 	at javafx.base@18.0.1/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
> 	at javafx.controls@18.0.1/javafx.scene.control.ComboBoxBase.setShowing(ComboBoxBase.java:187)
> 	at javafx.controls@18.0.1/javafx.scene.control.ComboBoxBase.show(ComboBoxBase.java:395)
> 	at javafx.controls@18.0.1/com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior.show(ComboBoxBaseBehavior.java:287)
> 	at javafx.controls@18.0.1/com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior.mouseReleased(ComboBoxBaseBehavior.java:243)
> 	at javafx.controls@18.0.1/javafx.scene.control.skin.ComboBoxBaseSkin.lambda$new$2(ComboBoxBaseSkin.java:72)
> 	at javafx.base@18.0.1/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
> 	at javafx.base@18.0.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
> 	at javafx.base@18.0.1/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
> 	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
> 	at javafx.base@18.0.1/javafx.event.Event.fireEvent(Event.java:198)
> 	at javafx.graphics@18.0.1/javafx.scene.Scene$MouseHandler.process(Scene.java:3881)
> 	at javafx.graphics@18.0.1/javafx.scene.Scene.processMouseEvent(Scene.java:1874)
> 	at javafx.graphics@18.0.1/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2607)
> 	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
> 	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
> 	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
> 	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
> 	at javafx.graphics@18.0.1/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
> 	at javafx.graphics@18.0.1/com.sun.glass.ui.View.notifyMouse(View.java:937)
> 	at javafx.graphics@18.0.1/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at javafx.graphics@18.0.1/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
> 	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by oasuncion** [comment]
NPE fixed. It will be delivered in v2.0.0
